### ISSUE TITLE
Upgrade Jquery and Jquery UI

### ISSUE THREAD

**Issue by RomelSan** [hacst/HTML5HASH#2]
Hi,
Can you please upgrade jquery and jquery UI?

Thanks :)

**Comment by hacst** [comment]
Hi. Any specific reason to do so? Seems to still work great with what browsers I tested it with.

**Comment by RomelSan** [comment]
I want to add bootstrap (latest version 3.3.6) but the app stops working.
I know a little javascript but i am not that good.
The main reason to upgrade is to make the app responsive and to provide cosmetic changes.
I am trying to make it work but no luck.
